version: '3.8'
services:
  bonus-service:
    build:
      context: ../..
      dockerfile: docker/bonus/Dockerfile.bonus
    env_file: 
      - ../../.env.bonus
    volumes:
      - ../../logs:/app/logs
      - ../../test_bonus_config.json:/app/test_bonus_config.json
    restart: unless-stopped
    network_mode: "host"